version: '3.8'

services:
  # Frontend
  frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
